### ISSUE TITLE
Line 29: Undefined mixin 'transition'

### ISSUE THREAD

**Issue by sisihagen** [thoughtbot/refills#370]
Hello, 

i try to run refills but ever come the mistake "Undefined mixin" in Grids, Flex Grids come "Undefined Display".

layout.scss
~~~
@charset "utf-8";

@import "bourbon/bourbon",
		"neat/neat", 
		"base/base",
		"_modules/reset", (normalize)
		"_modules/header", (CENTERED NAVIGATION)
		"_modules/grid"; (GRID ITEMS)
~~~

shell with append trace command 

~~~ bash
^Csiefke@sisibox ~/Dokumente/projects/test-website $ sass scss/layout.scss css/layout.css --trace
scss/_modules/_grid.scss:29:in `transition': Undefined mixin 'transition'. (Sass::SyntaxError)
	from scss/_modules/_grid.scss:29
	from scss/layout.scss:8
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:349:in `block in visit_mixin'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:98:in `block in with_mixin'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:98:in `with_mixin'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:347:in `visit_mixin'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `map'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `map'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:326:in `map'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:88:in `block in with_import'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:88:in `with_import'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `map'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:157:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:8:in `visit'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/root_node.rb:29:in `render_with_sourcemap'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/engine.rb:378:in `_render_with_sourcemap'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/engine.rb:295:in `render_with_sourcemap'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/exec/sass_scss.rb:414:in `run'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/exec/sass_scss.rb:63:in `process_result'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/exec/base.rb:52:in `parse'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/lib/sass/exec/base.rb:19:in `parse!'
	from /home/siefke/.gem/ruby/2.0.0/gems/sass-3.4.21/bin/sass:13:in `<top (required)>'
	from /home/siefke/.gem/ruby/2.0.0/bin/sass:23:in `load'
	from /home/siefke/.gem/ruby/2.0.0/bin/sass:23:in `<main>'
~~~

Follow versions is installed:

~~~ bash
siefke@sisibox ~/Dokumente/projects/test-website $ gem list --local | grep bitters
bitters (1.2.0)
siefke@sisibox ~/Dokumente/projects/test-website $ gem list --local | grep bourbon
bourbon (4.2.6)
siefke@sisibox ~/Dokumente/projects/test-website $ gem list --local | grep neat
neat (1.7.4)
~~~

Has someone an idea? 

Silvio

**Comment by tysongach** [comment]
Hi @sisihagen! I don’t believe you can chain Sass imports the way you have it. Have you tried declaring `@import` before each partial, as shown below?

```diff
- @import "bourbon/bourbon",
-         "neat/neat", 
-         "base/base",
-         "_modules/reset", (normalize)
-         "_modules/header", (CENTERED NAVIGATION)
-         "_modules/grid"; (GRID ITEMS)
+ @import "bourbon/bourbon";
+ @import "neat/neat";
+ @import "base/base";
+ @import "_modules/reset";
+ @import "_modules/header";
+ @import "_modules/grid";
```

**Comment by sisihagen** [comment]
Is same:

~~~
siefke@sisibox ~/Dokumente/projects/test-website $ sass scss/layout.scss css/layout.css
Error: Undefined mixin 'transition'.
        on line 29 of scss/_modules/_grid.scss, in `transition'
        from line 29 of scss/_modules/_grid.scss
        from line 8 of scss/layout.scss
  Use --trace for backtrace.
~~~

The sass imports run in other projects too.

Silvio

**Comment by tysongach** [comment]
@sisihagen Alright. Well, `transition()` is part of Bourbon; are we sure Bourbon is properly being imported? Is the code open-source somewhere that we can see?

**Comment by sisihagen** [comment]
https://github.com/sisihagen/test-site > is the page (i want change my origin page and this is crazys thing. There all work well but test page not.)

**Comment by tysongach** [comment]
@sisihagen Ah! You are using the Bourbon 5 beta, not `4.2.6` as indicated above.

In that case, the `transition` mixin has been removed from Bourbon 5 which is why you are seeing this error. So, couple of notes/options:

1. Refills is not _currently_ immediately compatible with Bourbon 5 (it uses a handful mixins that are removed, as you’ve found).
2. You could use Bourbon 4.x, which _is_ compatible with Refills today.
3. Or, just remove the use of the removed mixins and continue using Bourbon 5 (the `transition` mixin isn’t really needed any way since [unprefixed support is strong these days](http://caniuse.com/#feat=css-transitions)). I’m working on Bourbon 5 compatibility for Refills, but it won’t be out/ready for a couple of weeks.

**Comment by sisihagen** [comment]
Oh okay, yes this i have read but and install bourbon 4 but i forget delete the folders and run new bourbon neat bitters install. Ok im sorry for stole your time. 

Silvio

**Comment by tysongach** [comment]
@sisihagen No worries; happy we got it resolved! Let us know if you have any other questions.
